# Generated by Django 5.2.5 on 2025-08-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outro', 'Outro'), ('Prefiro não informar', 'Prefiro não informar')], max_length=20)),
                ('q1', models.CharField(max_length=1)),
                ('q2', models.CharField(max_length=1)),
                ('q3', models.CharField(max_length=1)),
                ('q4', models.CharField(max_length=1)),
                ('q5', models.CharField(max_length=1)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
